### PR TITLE
fix 'test .expected and .actual'

### PR DESCRIPTION
**Pull request by rafmagana**
when I run `make test` this test failed with this error:

✖ 1 of 46 tests failed:

  1)  test .expected and .actual:
     TypeError: object is not a function
      at Object.CALL_NON_FUNCTION (native)
      at Context.<anonymous> (/Users/raf/projects/js/should.js/test/should.test.js:71:20)
      at Test.run (/Users/raf/projects/js/should.js/node_modules/mocha/lib/runnable.js:158:32)
      at Runner.runTest (/Users/raf/projects/js/should.js/node_modules/mocha/lib/runner.js:292:10)
      at /Users/raf/projects/js/should.js/node_modules/mocha/lib/runner.js:336:12
      at next (/Users/raf/projects/js/should.js/node_modules/mocha/lib/runner.js:220:14)
      at /Users/raf/projects/js/should.js/node_modules/mocha/lib/runner.js:229:7
      at next (/Users/raf/projects/js/should.js/node_modules/mocha/lib/runner.js:179:23)
      at Array.<anonymous> (/Users/raf/projects/js/should.js/node_modules/mocha/lib/runner.js:197:5)
      at EventEmitter._tickCallback (node.js:126:26)

not sure why you were using `assert` there though.

After the fix:

.............................................

✔ 45 tests complete (46ms)

### CODE REVIEW

**Comment by tj** [comment]
same thing, the assert should pass

**Comment by TooTallNate** [comment]
@rafmagana You're probably on node v0.4.x, where the `assert` module isn't a function yet.

**Comment by rafmagana** [comment]
yeah, I work on 2 projects using v0.4.2, the other ones uses 0.6.x, I know it would have been better to upgrade to 0.6.x and test should.js with newer versions, but I still think that if both ways do the same thing but one way doesn't work with older versions of node, it'd be good to support them. Thanks though.

**Comment by tj** [comment]
normally I'd agree but 0.4.x is pretty dead since 0.8.0 will be soonish

**Comment by rafmagana** [comment]
hehe, yeah, I'm stuck in v0.4.2 with some apps, but I think it's time to upgrade. Thanks.
